---
- hosts: all
  become_method: sudo
  become: true
  tasks:
  - name: turn off install_recommends for apt
    lineinfile: dest=/etc/apt/apt.conf.d/01norecommend state=present create=yes line="{{ item }}"
    with_items:
      - APT::Install-Recommends "0";
      - APT::Install-Suggests "0";
      
  - name: emacs snapshot repo
    apt_repository: repo={{ item }} state=present
    with_items:
      - "ppa:ubuntu-elisp/ppa"

  - name: emacs snapshot repo key
    apt_key: keyserver=keyserver.ubuntu.com id=062D648FD62FCE72
    
  - name: core packages
    apt: update_cache=yes cache_valid_time=3600 name={{ item }} state=present
    with_items:
      - curl
      - wget
      - git
      - screen
      - finger
      - emacs-snapshot-nox
      
  - name: safe upgrade
    apt: upgrade=safe